[project]
name = "phishpedia"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
python = ">=3.8"
pip = "*"
setuptools = "*"
wheel = "*"
numpy = "1.23.0"
requests = "*"
scikit-learn = "*"
spacy = "*"
beautifulsoup4 = "*"
matplotlib = "*"
pandas = "*"
nltk = "*"
tqdm = "*"
unidecode = "*"
gdown = "*"
tldextract = "*"
scipy = "*"
pathlib = "*"
fvcore = "*"
lxml = "*"
psutil = "*"
Pillow  = "8.4.0"


[pypi-dependencies]
"flask" = "*"
"flask-cors" = "*"
"pycocotools" = "*"
"opencv-python"= "*"
"opencv-contrib-python"= "*"
torch = { version = ">=1.9.0", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.10.0", index = "https://download.pytorch.org/whl/cpu" }

